name: Slack Pull Request Message

on:
  push:
    branches-ignore:
      - main

jobs:
  notify-resolve:
    runs-on: ubuntu-latest

    steps:
      - name: Check commit message
        id: check_message
        run: |
          commit_message="${{ github.event.head_commit.message }}"
          if echo "$commit_message" | grep -q "Pull Request"; then
            echo "send_notification=true" >> $GITHUB_ENV
          else
            echo "send_notification=false" >> $GITHUB_ENV
          fi

      - name: Post text to a Slack channel
        if: env.send_notification == 'true'
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: "#slack-test"
            text: |
              ✅ **Pull Request initiated from `${{ github.ref_name }}` branch! See the commit message below**
              - **Commit Number:** `${{ github.sha }}`
              - **Commit Message:** `${{ github.event.head_commit.message }}`
              - **Committed by:** `${{ github.actor }}`
              - **Commit URL:** https://github.com/${{ github.repository }}/commit/${{ github.sha }}
